from app.core.events import SalesDocumentCreated, EventBus
from app.database import SessionLocal
from app.models.inventory import StockOnHand
from app.models.abasto import PurchaseRecommendation, RecommendationStatus
from sqlalchemy.orm import Session
import logging

logger = logging.getLogger(__name__)

# --- BUSINESS RULES ---
# TODO: Load these from a dynamic rule engine or database table (ProductVariant.min_stock)
DEFAULT_MIN_STOCK = 10
DEFAULT_REORDER_QTY = 50

def check_reorder_levels(event: SalesDocumentCreated):
    """
    Analyzes stock levels after a sale and generates purchase recommendations if needed.
    """
    logger.info(f"Abasto: checking reorder levels for Sale {event.sales_document_id}")
    
    db: Session = SessionLocal()
    try:
        for item in event.items:
            variant_id = item.get("variant_id")
            if not variant_id:
                continue

            # 1. Check current stock level
            # We assume the sale already deducted stock in the transaction, 
            # so we are reading the "after sale" state.
            stock_record = db.query(StockOnHand).filter(
                StockOnHand.variant_id == variant_id
            ).first()
            
            if not stock_record:
                logger.warning(f"Abasto: No stock record found for {variant_id}")
                continue
                
            qty_current = stock_record.qty_on_hand
            
            # 2. Check Rule: "Is Stock Low?"
            # For MVP, we use a global constant. In v2 this should be `stock_record.min_limit`
            if qty_current < DEFAULT_MIN_STOCK:
                logger.info(f"Abasto: Low stock detected for {variant_id} (Qty: {qty_current} < {DEFAULT_MIN_STOCK})")
                
                # 3. Check if we already have a PENDING recommendation to avoid duplicates
                existing = db.query(PurchaseRecommendation).filter(
                    PurchaseRecommendation.variant_id == variant_id,
                    PurchaseRecommendation.branch_id == stock_record.branch_id,
                    PurchaseRecommendation.status == RecommendationStatus.PENDING
                ).first()
                
                if not existing:
                    # 4. Generate Recommendation (Event-Driven Decision)
                    rec = PurchaseRecommendation(
                        variant_id=variant_id,
                        branch_id=stock_record.branch_id,
                        trigger_event_id=event.event_id,
                        reason=f"Stock ({qty_current}) below Threshold ({DEFAULT_MIN_STOCK})",
                        suggested_qty=DEFAULT_REORDER_QTY,
                        status=RecommendationStatus.PENDING,
                        notes="Auto-generated by Abasto Engine"
                    )
                    db.add(rec)
                    db.commit()
                    logger.info(f"Abasto: Generated PurchaseRecommendation for {variant_id}")
                else:
                    logger.debug(f"Abasto: Pending recommendation already exists for {variant_id}")
            else:
                logger.debug(f"Abasto: Stock OK for {variant_id} ({qty_current})")
                
    except Exception as e:
        logger.error(f"Abasto: Error processing event: {e}", exc_info=True)
    finally:
        db.close()

# Start Listening
def setup_abasto_subscribers():
    EventBus.subscribe(SalesDocumentCreated, check_reorder_levels)
