export const PAY_METHOD_LABELS: Record<string, string> = {
  CASH:         'Efectivo',
  CARD:         'Tarjeta',
  TRANSFER:     'Transferencia',
  STORE_CREDIT: 'Crédito tienda',
  CHECK:        'Cheque',
  OTHER:        'Otro',
}

export const ROLE_LABELS: Record<string, string> = {
  ADMINISTRADOR: 'Admin',
  DUEÑO: 'Dueño',
  GERENTE: 'Gerente',
  CAJERO: 'Cajero',
  VENDEDOR: 'Vendedor',
  SOPORTE_OPERATIVO: 'Soporte',
  CLIENTE: 'Cliente',
}

export const BRANCH_COPY = {
  cockpit: {
    payNow: 'Cobrar',
    backToHome: 'Volver a Mi día',
    shiftOpen: (mins: number) => `Caja abierta · ${formatDuration(mins)}`,
    shiftClosed: 'Sin caja abierta',
    openShift: 'Abrir turno',
    closeShift: 'Cerrar mi turno',
    today: 'Mi día',
    salesToday: 'Ventas del turno',
    salesTickets: (n: number) => `${n} ${n === 1 ? 'ticket' : 'tickets'}`,
    avgTicket: 'Ticket promedio',
    returnsToday: 'Devoluciones del turno',
    goalLabel: 'Meta del turno',
    goalNone: 'Sin meta configurada',
    goalOf: (total: string) => `de ${total}`,
    paymentMethods: 'Métodos de pago',
    topProducts: 'Top productos',
    noPending: 'Sin pendientes',
    closingChecklistTitle: 'Cierre de turno',
    closingStep_cash: 'Cuenta el efectivo en caja',
    closingStep_card: 'Concilia totales con la terminal',
    closingStep_z: 'Imprime el corte Z',
    closingStep_expense: 'Registra los gastos del día',
    closingCashLabel: 'Efectivo contado',
    quickAccess: 'Accesos rápidos',
    alertsTitle: 'Alertas',
    error: 'No pude cargar tu día. Reintenta o avisa al admin.',
    greetingMorning: 'Buenos días',
    greetingAfternoon: 'Buenas tardes',
    greetingEvening: 'Buenas noches',
    shiftOpenPill: 'Turno abierto',
    shiftClosedPill: 'Sin turno',
    cobrarAhora: 'Cobrar ahora',
    abrirTurno: 'Abrir turno',
    greeting: (name: string) => `Hola, ${name}.`,
  },
  alerts: {
    low_stock: (n: number) => `${n} producto${n === 1 ? '' : 's'} por agotarse`,
    no_branch_price: (n: number) => `${n} producto${n === 1 ? '' : 's'} sin precio en sucursal`,
    quote_expiring: (n: number) => `${n} cotización${n === 1 ? '' : 'es'} por vencer hoy`,
    cash_variance: (amt: string) => `Diferencia de caja del último cierre: ${amt}`,
    severity: {
      high: 'alta',
      medium: 'media',
      low: 'baja',
    },
  },
  pages: {
    sales: 'Mis ventas',
    cash: 'Mi caja',
    returns: 'Devoluciones',
    products: 'Buscar producto',
    reports: 'Reportes',
    printer: 'Impresora',
    cashKpis: {
      // existing — kept for any out-of-scope consumers
      salesToday: 'Ventas del turno',
      expected: 'Efectivo esperado',
      difference: 'Diferencia turno',
      weekShifts: 'Turnos 7 días',
      // new — used by the redesigned KPI grid
      cashShift: 'Efectivo del turno',
      totalSales: 'Ventas totales',
      inflows: 'Entradas',
      outflows: 'Salidas',
    },
    cashHistory: {
      title: 'Mis turnos pasados',
      closedAt: 'Cierre:',
      sales: 'Ventas',
      diff: 'Diferencia',
      reprint: 'Reimprimir',
    },
    cashWeekChart: {
      title: 'Diferencias de la semana',
      noSession: 'Sin turno ese día',
      legend: 'Sobrante · Rojo = faltante · Gris = sin turno',
    },
    cashMovements: {
      title: 'Movimientos del turno',
      empty: 'Sin movimientos en este turno',
      registerIn: '+ Entrada',
      registerOut: '− Salida',
      modalTitleIn: 'Entrada de efectivo',
      modalTitleOut: 'Salida / Gasto',
      amount: 'Monto',
      concept: 'Concepto',
      submitIn: 'Registrar entrada',
      submitOut: 'Registrar salida',
    },
    weekSalesChart: {
      title: 'Efectivo cobrado · 7 días',
      legend: 'Suma de cash sales por día (turnos cerrados + turno actual)',
      noSession: 'Sin turno',
    },
    cashReprint: {
      noPrinter: 'Configura tu impresora local primero.',
      success: 'Reimprimiendo corte…',
      error: 'No pude reimprimir. Verifica que el agente esté corriendo.',
    },
  },
  states: {
    loading: 'Cargando…',
    empty: 'Sin movimientos',
  },
  products: {
    create: 'Crear producto',
    edit: 'Editar',
    detail: 'Ver',
    activate: 'Activar',
    deactivate: 'Desactivar',
    close: 'Cerrar',
    searchPlaceholder: 'Buscar por nombre, SKU o código…',
    variantsTitle: 'Variantes',
    noVariants: 'Sin variantes registradas.',
    toggleError: 'No se pudo cambiar el estado. Intenta de nuevo.',
    kpiTotal: 'Total SKUs',
    kpiActivePOS: 'Activos en POS',
    kpiNoPrice: 'Sin precio',
    kpiNoImage: 'Sin foto',
    noResults: (q: string) => `Sin resultados para "${q}"`,
    emptyHint: 'Escribe para buscar productos.',
  },
  sales: {
    rangeToday: 'Hoy',
    rangeWeek: 'Esta semana',
    kpiTotal: 'Total ventas',
    kpiTickets: 'Tickets',
    kpiAvg: 'Ticket prom.',
    kpiTopMethod: 'Top método',
    itemsLabel: 'Artículos',
    reprint: 'Reimprimir ticket',
    noPrinter: 'Sin impresora configurada',
    noPrinterToast: 'Configura tu impresora local primero.',
    reprintSuccess: 'Reimprimiendo…',
    reprintError: 'No pude reimprimir. Verifica que el agente esté corriendo.',
    returnAction: 'Registrar devolución',
  },
  openShiftModal: {
    title: 'Abrir turno',
    openingLabel: 'Monto inicial en caja',
    notesLabel: 'Notas (opcional)',
    submit: 'Abrir turno',
    success: 'Turno abierto',
    error: 'No se pudo abrir el turno',
  },
} as const

function formatDuration(mins: number): string {
  const h = Math.floor(mins / 60)
  const m = mins % 60
  if (h === 0) return `${m}m`
  return `${h}h ${String(m).padStart(2, '0')}m`
}
